apiVersion: v1
kind: Secret
metadata:
    name: newrelic-license
type: Opaque
stringData:
    license-key: ENC[AES256_GCM,data:przhzJYP/ENGy4SSAulc43C+HdRuPfVIMCSN7hyLn1ydnL28uP8GAg==,iv:wJgTKiKg67QF/iQR9KGcfgFK8AEclOkAvqsfdSsZOz4=,tag:/1UhxGaH5U6cXVnxiimaog==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QUVzRWVYYzB1T2NmeTRq
            YVdQR2EyWDNKMWp1SHNMR0R0NWF0WlpqRURNCmlrbmhzaXpuQllqaDdBVkZqbzc1
            TWh1Tno0N21jeTd5aW02THZqOWM5UVUKLS0tIFdISVIzUlVQaXpmd0FybHc3L0VN
            RDE5TmZhQ2lpUmlqTUJRTFFGWEtPOWcK06m5u/4KanTFeHXe2zWCqrfEbTZBLHF/
            ahMtqUghaKU4IhPnEYzwkEtQpPtlsoP/dtdOupuWN5+cgd9Lk4TCMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:04:59Z"
    mac: ENC[AES256_GCM,data:lr+5mWDDxRVvWtC+cZDf6ZB4C5K0ygZJN4IeYuZGWEe7m0fURtFDoqB2cRX6lbAn2SirpDgD3H29wkKXmwk6DNZ07XDv+wyP/2iXC7BkI7/gGzFjhYOggJ/uLvJQxn7efEJbTx1NXh5hqlBal7yxNRHAG/ii+xPuePU8zzbU310=,iv:aplQwCUhe4sa95LzCQXkkD/OpSC4X+jJj51isJOEv0E=,tag:GEN1QZzvfw2oK4diF9ha+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2