apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-server-auth
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:I83CRHr/amxtuw==,iv:YZhbNreqVfgE1EFrcxfMVQXTeqqvHgxk5WtmxHhU2Wc=,tag:N2I4TXCLlYa4LrJyNFEQWw==,type:str]
    password: ENC[AES256_GCM,data:k9aU16ZFcYnzXvZsrbNVtGFcEitPV4hy,iv:PjL1J+yKsmtTsJ+d5o3yHD+xZMSk46jQwRx1+fuZBbM=,tag:Ko/CizQY+p3J+vrvfOg7Pg==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNkZ1eGNrOFI5Zi9mYVcz
            K3Zma3pCRzljRTlSSmVoU1E3VERZdktab2k0ClhiWElqZTJ6TG4ycU9DTjBaL1Zp
            L05aRFhUUDNwd1R1WmZUNE45NC84aTAKLS0tIFMwNDdqQVAxZDNlVS9aSnFjc0Iv
            S3ZYWE5Bd3UrcWE2UjMycmxNWnhDTEkKKuRerZjqbHyXK9uNMcoM/U7nA0MIgf1a
            ayqPpA9uNODmqan5dKHZwCtSTTzepGldi6kPD0QLSIPKw6Ne/ni1IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T19:31:58Z"
    mac: ENC[AES256_GCM,data:24C1Nlt+MNF5KFNOiSYdvJkwgbK0Yqn0yaE/fDdDUpKthykOZrLpkA/Mq35fahqNkidIDkw1TMPLA6tlyH2fO72lNDR+ewYCdqtbfeCEN1yA6U2JRq+hJrFUYm0pNTfJ2zhdCLa9wRlZKHaeh6S7GXdTVzRObAUCdc0Ow1251WY=,iv:jGgq4b7owDMLdf/uaEkHCbkWudZZpA4FcKUl7k9jZGE=,tag:SVQNJBg3AHAkMmxmVq02Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
