apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-validator-auth
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6HlYVgBhMH/QFw0NCQ==,iv:BSZxaxVXkU0CkYy88A+jNry4oq4/qKNr6LZZavUaPc0=,tag:q30dEOIHWNktj3eqkUHZiA==,type:str]
    password: ENC[AES256_GCM,data:rTN9B0sayzfF1whvNQRFkGhXw8joITJ6,iv:oNxibjYw5FgqCFMTtK/fIhmEZyJCqqKdpUjy9uCQ5/w=,tag:ZZbf0RWPjG+gR2RDWFI5yw==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZXp6MVdqeENCV2M3VERQ
            NHRRYkZZNkVjNVRBd2diUi9HQzB4d1ErVlJZClhVTWlpcEdVblRYQ1B2NWhLa2Fs
            dFJZODdzanNPUFRORFZ1U202dXV1bmsKLS0tIHVNRDM0Rnd0NEsyRDZGeFVzdFk1
            cFc5akUvcHJwcXZRYnZTY1hpOUNhd3MKSpePp1Xf4qV7C6ci1zgB1otzOlNOg4cT
            Tx1XIAMHOcbmZopPNoD5pb/l5GNDCWwlvYePQRy28PkgTJ5LzCJd1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:27:13Z"
    mac: ENC[AES256_GCM,data:2L9Wm8USGDroeyaHXV38Wl7i+h3urUbdOuYdJwwI4r91iUIF27GgvHethPAT5uQXhcmFzB4bFFSqWn1kLCouwIlmdKBdt+pylQ5ygDHziF22uQ/tDZzoTjHm+I+J3pvhim6KaJwmoetfMso7Vsp4oUvhDad/v09ggfjbAarfa4M=,iv:AQpg//GZDp5TejgLu8tlbHuBfoSznZUxmxb9rgz2MjQ=,tag:Q+SxZ8ziEtm2+fSqfrWjrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
