apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-server-superuser
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:KQPkAeKGGXM=,iv:7KEJDgKkrmaHH8WgFw/KTk+d3r0xc1AyzWFeJYO7Rz8=,tag:bWtdidO4ykhW1xGFoX/aDw==,type:str]
    password: ENC[AES256_GCM,data:8awcZESSOFRdm9/4I8u3GfPJ1HCTCqVR,iv:rilMNt3FZlxBhcLtWgxpvjpEhetUVQ1H4nIveq6qJlo=,tag:zB6GBqke5UoQOmyIpoPkhA==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETjZsejZFWlJ0dGVrYVg5
            NXBHQzFMN3poVUhxVWtIM3VEdFVUWCs5OVhrCjZCUmpWUWJzRlZCR0VISndTOVBj
            T2NqSW43SjF3ZGR2SVdIV2Y2Q1lycUUKLS0tIGFZMTlObFdGaDByS3RIcTMvZWlS
            WVhRaUg3cmQ5dEwyMmhvbFl1VURJa2sKxEbPW6FuS4fHTWgmjIV/Hf4tycahSpKO
            c6gGodSjXnsxDs8eEgX6KAingC6BIaEWxkGNuT2whWXUeWQiy31fmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:21:35Z"
    mac: ENC[AES256_GCM,data:rJgZ1Hqba5+JIY9SfZZ3C/4Ds7/qcbsmxoJl+bNbwF+fg0+H0zIrgjMk/f1YxrgzMy16Z5Ro/SKwjZvmEJl9nfqpfx9YnOeBzxThZPWdtoNT5zyU1I2rg/eG7zMyLkyxudglJulXFJq5GzNMLSUhbJr7m+SaI/sV3zBg69OwUNg=,iv:YroAE36OU3+zuNc961sxKI2CJlvTXPnB6tQFXpt3ztQ=,tag:K9Bzq4NCY+UGMrmQ6SayMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
