apiVersion: v1
kind: Secret
metadata:
    name: scim-postgres-validator-superuser
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:uLwKWrVQmxk=,iv:XkX9Hj4mhjEJOGhq4jI32U4qCvjyHa11B+gC34CMFtY=,tag:/SEuOjLW3pP4ps215PqKWA==,type:str]
    password: ENC[AES256_GCM,data:i2rxn3u/vw7Ws4KwZKQ9cSL6ziC6uIBrY9ei6HdooQ==,iv:zproIrF/Q151X1BnQNc/rG2U3pf9FRUVZ53aK40NEqM=,tag:VH+UJQgHUzvB0Gb6GscUfQ==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBYkZDN3R3UHhSWWZTWTB3
            R0tzVDRQamZSQTlJTHdPdDczV1lIUUZnL3dVCkQzd0pTZkptdG1RanNGNVRiL21U
            L0tveVlVbkRGVkFrK2ltM2V6N2cvUlkKLS0tIGJJdVg4WkJNbEtlanlOWDNMVkQx
            M1hTNGRvODRlQjEremIzWHlpakNYYkkKM330GJyMKPgIqngPDuoa6sAyuiXkPaNg
            vawhMJgUiu5Ustk76lPF4dvsbtnD0UC7FPhG6U48iYShIjmtEIUiug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:16:09Z"
    mac: ENC[AES256_GCM,data:F2fE3LoeFkNViweKtjkxiiDsI9OU1LU/yi17iHhWQXb3UbhrPbp8QvtIev0DU3fsPD+35k6cliosOIQT7cDRiFNRpf0UMwM8TbdVIHauPO+JeM9tgRFzIUf5xERlwFTLwg8MPrjmDNouBn1BHC2ZwdmyuJPK03T1e+Iw0hE24d0=,iv:Hd9Ic90jUPQjCow3GTJfrvi36DPg3nq6ugselbtGL/Y=,tag:Va/Ia2lE++sERbwcu+YJZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
