apiVersion: v1
kind: ConfigMap
metadata:
  name: scim-server-impl-spring
data:
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "35"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_KEEPALIVE_TIME: "300000"
  APP_RATE_LIMIT_REQUESTS_PER_SECOND: "1000"
