apiVersion: v1
kind: Service
metadata:
  name: scim-server-impl
  labels:
    app.kubernetes.io/name: scim-server-impl
    app.kubernetes.io/component: scim-server-impl-spring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: scim-server-impl
  ports:
    - name: http
      port: 8080
      targetPort: http