apiVersion: v1
kind: Secret
metadata:
    name: secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:4bzqsIuZ3vRtxx1NSZ7D+j++eOZ0QcXV5NY4Ri0a/1fmnk0CLYNLlZWPU+C1vuZswRNl8IrDux44N800Fngq10p5m9i0uD2IsV5bY00ybql4re0hurTsxINW6VN+2SPdHBSupQjwvJfzWuNcxXdznhjvgj/kfE3LwXl1auXC8vF+UXUXBqdM2VDymHqvq9hEqu3FiVUD2dT1s+abShXEM6txe9a0Q0OaNgwYzsiCWtd+/NqVvS8P2g==,iv:IJoYvmFX2JfuycB4Ke4InsjyrI+cSFBEePsoJtTgLC4=,tag:/rLuqQ4HEWrtmKN567DmZw==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNUZyMGwwakJ5Sm03SzV3
            SUgyaEFyVGNHREYzLzhoMU1qU2VBSVo5aVJjClllMWRLclJVTWJzaWthUWRNaXBZ
            SndaaFJMUXE3dmxMY0g0TzNoNUJQL1UKLS0tIGF4dmJSQkFMaU9UVGJuckdoYXlY
            MGpoTmtGOGJ4OTdKWmxGUkRCaWZrd1kK0ITZQ6RTjz/mi/GSvhSedIX+qbiNNjqv
            qs88i+OszVEpcW4oXItxKhd/kUg7B8n+gvlkRSs+uY04PGuqgIXBVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-27T16:55:22Z"
    mac: ENC[AES256_GCM,data:lbTD09rHsgEZOu+GCOyGZ/blEHiClI3ADILtb/EWPZ0rS2obVWPowO2khmGr7ZZ3SoP8mDgnEt1DMf4y1c2pZnmNphykpbHU55SyafzpeCxGivP9houlJlFysL5FvsJCLxKvi7D0VTrf+FWI/2dSw4heLEI+iupPm2dhN4oopqw=,iv:wKxzREttNV097USfG60c0aQ/BH1xpwUlngOeDgGOc9k=,tag:5NvPDHeTlHyokQ7xhnkHLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
