apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: scim-newrelic-license-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/newrelic-license.sops.yaml