apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backup
  - database
  - scim-server-ui-spring
  - scim-validator-ui-spring

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: scim
      app.kubernetes.io/environment: k3s

images:
  - name: edipal/scim-server-ui-spring
    newTag: "v0.0.4"
  - name: edipal/scim-server-db
    newTag: "v0.0.3"
  - name: edipal/scim-validator-ui-spring
    newTag: "v0.0.1"
  - name: edipal/scim-validator-db
    newTag: "v0.0.2"