apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: scim-validator-ui-spring
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/secret.sops.yaml