apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-custom
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"