apiVersion: v1
kind: Secret
metadata:
    name: scim-validator-ui-spring
type: Opaque
stringData:
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:Rm9Wk2YhPlIuPqmwgo1for8T6bFm72vDFVU9b9/xPog=,iv:/6F4KMS+wqBPnz4+uXMKAV4uxYqMTMXU71C1EGEjhb4=,tag:UX70hLsCqNQoB8nnngW/WQ==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:FlMVrzGQsGwmNlO2DV1N8OSNo2kBQA2hN8ZxmwYmMVDE9OvpssryVWJrhQYyYvh+muxL/5ZnHPnJM2V9Go+z0A==,iv:C/9AS1E2IE5L13rmt6inbbEtci2q8KZ+Kq9v7pKq9Dw=,tag:ItXJ6MNNa00+yOAwoOaM9Q==,type:str]
    AUTH0_ISSUER_URI: ENC[AES256_GCM,data:vkxGnH6Bsp9Xpz8oBaZDJpZJIdbsE8M/ZtnDSGk=,iv:NrZdlKqPcRyA+1USzn8hWlULsO+/kxzeNdo2wohNHhg=,tag:Y7hLZnj5CxptCaziJ8ZIaQ==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSk9qZHFxaVZ5RnpTKzhP
            QWUyWTNSZ0JMb1VOQkN0dkxndDJ5TkhGL0VVCmhyWWlCN2xlem40ZzQ2cS81aWgv
            UXA3SUQ1RmhjeVpxcDhPZ0RpR2pnTU0KLS0tIEMxWlcyVHFxOTlyOWFYUFdBWjdX
            VExGZGtXWWJXOHJkb1paZHhTRHViNXMKoJYy5PatO+SFoJy93IUkqYAt1JZlexnM
            yVmxa66O6j9J5KGmgWuCcGF4AVLGql58QZqXElX2voPY4Hg2C/LDHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T15:58:54Z"
    mac: ENC[AES256_GCM,data:7F0LArsPpJlvMC1I3qBAmSBpJrfCb84N4k7f5hMuGhl638jjr2aNAJZIchIdvY0oeQXOJCbCTkQ7CPDLyJOPMWndnu53P2+Nes0wNS+QI+4UwRQoYv66mqaWoe316zV0ZNwp0PjrOJX5/wSsbaMHONS2RbTwTenIg4QEo8KBIEE=,iv:GKA+vk2vDAlVfjmDeN5OLdrIKVPD8mLlfs8FdVjMqJc=,tag:f/fa4smzMly+/oDXhXtIjA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
