apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: scim-database-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - secrets/scim-postgres-server.sops.yaml
  - secrets/scim-postgres-server-superuser.sops.yaml
  - secrets/scim-postgres-validator.sops.yaml
  - secrets/scim-postgres-validator-superuser.sops.yaml