apiVersion: v1
kind: Secret
metadata:
    name: scim-server-ui-spring
type: Opaque
stringData:
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:5V8zE+VVVCAd79vTloTNdBaNCTUNkx2/vmbThMMtDzk=,iv:i1dL4uaV5cBL5PTf2ZZk+ElkuFMjjJ1r/qFArbby6Tk=,tag:+swsxiuEESokN2Gq1GrgtQ==,type:str]
    AUTH0_CLIENT_SECRET: ENC[AES256_GCM,data:Nd3H1t20KPaeWiZVEcoiagXwOOtq48WmiqH6yx2rK+OieFW/WncN78pnRbbsM6hSvOsjeY/gvel2qw5S1wrBlw==,iv:Asq3T7i3h0S+e1HHTsIA6QALMbvoAHry1bQ0tDeeQvE=,tag:YFlcm+a243uLKBl8CDG+xA==,type:str]
    AUTH0_ISSUER_URI: ENC[AES256_GCM,data:g6dX7zTbpNKJhOzBMXEGGuiagqTdZYOKouuOKwU=,iv:XIV5LDlrVOnEf1ylpMSzfc6Cmt7LYI6UM73zrRAHXbM=,tag:0U+SQgcK+l9oDDcbF+Kqxg==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQXNVVVpvdFM4WHE0YjFu
            YlVxWjBzMFprZXZCcysrVDFOTHZpY2JQbDJ3Ckx3Tk9ack1XNjNvckFTejdUTytj
            dkR6aFdCYnd2OU53T0hQdmRBRG9ld28KLS0tIDBxNTZFM0xUclpxMVVuYjg1LzVN
            T2JreVVlVEt1S3J5LzZRekVSVFY4c0kKyOV5MRLGnYyWLyzcHa9UmfItp2d/hKsX
            b2duPUECnG01v19Hxkwo/UdJD/yIYgTvHpCl2oih/plqCO3baEmIqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T15:46:24Z"
    mac: ENC[AES256_GCM,data:/2IRbasz0Rv4SzmCtcO00XRXm2pDlk8X7xdCPhbE3PqfpdGICfYAHkVVgZTajoTa3fy1UfKxaBJ2IRkHhmd3FwkkqcLkR7lsYEnuz2lmDQBqoxHHP9M33djiZKeQjxsSf+U5HcN/A9ismkWop/cnjYx+RIZagyJlZVWdYh3vKvw=,iv:9WKZDpOYZXjTrt0uFeqxdDWtALXdMsU7wt1CxPygFT4=,tag:CEHmstR18jBE5wUy6XsREw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
