apiVersion: v1
kind: Secret
metadata:
    name: backup-secrets
    namespace: scim
type: Opaque
stringData:
    storage-box-user: ENC[AES256_GCM,data:tjQWHl7+efjjFNgT,iv:eDr5BlS/UrSvONtnBYlRYnYsQRs/mJKmPlMS/NaucZo=,tag:Pbi5Ga9QMnJ69/wj+Y9uQg==,type:str]
    storage-box-host: ENC[AES256_GCM,data:4F+F+NvJsIYlHMSx5LK6aoJk3l8dyhzf3iAMPuHVdA==,iv:GmjA7IXO0KpQj53lFKyVhWohZegNjRTfSPvWkk7PegQ=,tag:jG8bqx66mTy3O/7AKEX90w==,type:str]
    storage-box-path: ENC[AES256_GCM,data:Q2oPlP+YIXQfqJnw,iv:P+WcixJDko5/GGT9Dl8aN0d0kXbPYXWNxnkifbvGst8=,tag:GPkeCccjYoC0yfrGsihBqg==,type:str]
    restic-password: ENC[AES256_GCM,data:w89B5h15VpuzA/2mqT0PspXYGRFvpgg2,iv:DEduxMlx4Yi6k+JLHtmS9T6//qQduMxIV8jDoRDpGZA=,tag:Uuw1M3Zr4QIphEIczG0fDw==,type:str]
    ssh-password: ENC[AES256_GCM,data:Bw8swU9YR+i8ogJ1LfsvYI0qB9jVGPB1,iv:wptTDNoy2/UY411G6xuVAgyBpsUarHsw7xmSXo7s9D0=,tag:E49qXAV1UTBlW0AlbAAK+A==,type:str]
sops:
    age:
        - recipient: age1j0ka5qnc6cpldfavwstqg2u6k536ymxcjeatlceraa09dgvetq9s07jkkh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJM04ybS9zRzB6YXNVUXFX
            bHhhdGQ3SnBxeGdpYUxLMVZJTUNtczFpR2tvCktUTDBFWVRWak43NEh1SHEyS2xJ
            YklLcVc0VFNWQ3Z2Qk1xZEQ3b1hiajgKLS0tIFhyR2RKT2NMSTlMYkdKT3ZWWlhS
            aDJmLzJKTXlNendjQWYrRWptVzFpUXcKX1ngvAgHr4aa1l5IYVUDI4HfiAxB5DJ4
            TSo3MWTivq9/08clDLH0ms+u3Xe0K4OAZ6x67dDAhUmLxIJdzgkYrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T20:12:02Z"
    mac: ENC[AES256_GCM,data:MF/doRVy5apHgq6AAsj9Kr32ieMP+KWp0upclz/WMWFiRfS83ce1im4ZhDC+FR2clQzI31AfYCrUeavBPTEowbMNjhClDvOF+pM3xlBhsg6voq/S7BCYupI7sXtIPwCexlluETz/+1XqPGwRGL2loaWgzL+/yDeYg4JOtMUXmvA=,iv:dEBIj31TvKV8xYXypoCiW0RBbz4XV8Fmtnh1FNSjrmk=,tag:rbA51U636jJ/9fFtVyqZNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
