apiVersion: vi1.generators.kustomize.io/v1
kind: Ksops
metadata:
  name: backup-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - backup-secrets.sops.yaml